require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TaskDetailsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # TaskDetail. As you add validations to TaskDetail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaskDetailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all task_details as @task_details" do
      task_detail = TaskDetail.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:task_details)).to eq([task_detail])
    end
  end

  describe "GET show" do
    it "assigns the requested task_detail as @task_detail" do
      task_detail = TaskDetail.create! valid_attributes
      get :show, {:id => task_detail.to_param}, valid_session
      expect(assigns(:task_detail)).to eq(task_detail)
    end
  end

  describe "GET new" do
    it "assigns a new task_detail as @task_detail" do
      get :new, {}, valid_session
      expect(assigns(:task_detail)).to be_a_new(TaskDetail)
    end
  end

  describe "GET edit" do
    it "assigns the requested task_detail as @task_detail" do
      task_detail = TaskDetail.create! valid_attributes
      get :edit, {:id => task_detail.to_param}, valid_session
      expect(assigns(:task_detail)).to eq(task_detail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TaskDetail" do
        expect {
          post :create, {:task_detail => valid_attributes}, valid_session
        }.to change(TaskDetail, :count).by(1)
      end

      it "assigns a newly created task_detail as @task_detail" do
        post :create, {:task_detail => valid_attributes}, valid_session
        expect(assigns(:task_detail)).to be_a(TaskDetail)
        expect(assigns(:task_detail)).to be_persisted
      end

      it "redirects to the created task_detail" do
        post :create, {:task_detail => valid_attributes}, valid_session
        expect(response).to redirect_to(TaskDetail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved task_detail as @task_detail" do
        post :create, {:task_detail => invalid_attributes}, valid_session
        expect(assigns(:task_detail)).to be_a_new(TaskDetail)
      end

      it "re-renders the 'new' template" do
        post :create, {:task_detail => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested task_detail" do
        task_detail = TaskDetail.create! valid_attributes
        put :update, {:id => task_detail.to_param, :task_detail => new_attributes}, valid_session
        task_detail.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested task_detail as @task_detail" do
        task_detail = TaskDetail.create! valid_attributes
        put :update, {:id => task_detail.to_param, :task_detail => valid_attributes}, valid_session
        expect(assigns(:task_detail)).to eq(task_detail)
      end

      it "redirects to the task_detail" do
        task_detail = TaskDetail.create! valid_attributes
        put :update, {:id => task_detail.to_param, :task_detail => valid_attributes}, valid_session
        expect(response).to redirect_to(task_detail)
      end
    end

    describe "with invalid params" do
      it "assigns the task_detail as @task_detail" do
        task_detail = TaskDetail.create! valid_attributes
        put :update, {:id => task_detail.to_param, :task_detail => invalid_attributes}, valid_session
        expect(assigns(:task_detail)).to eq(task_detail)
      end

      it "re-renders the 'edit' template" do
        task_detail = TaskDetail.create! valid_attributes
        put :update, {:id => task_detail.to_param, :task_detail => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested task_detail" do
      task_detail = TaskDetail.create! valid_attributes
      expect {
        delete :destroy, {:id => task_detail.to_param}, valid_session
      }.to change(TaskDetail, :count).by(-1)
    end

    it "redirects to the task_details list" do
      task_detail = TaskDetail.create! valid_attributes
      delete :destroy, {:id => task_detail.to_param}, valid_session
      expect(response).to redirect_to(task_details_url)
    end
  end

end
